server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatbotdb
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

langchain4j:
  ollama:
    base-url: http://localhost:11434
    models:
      - mistral
      - gemma
      - llama3.2

ai:
  docs:
    location: "src/main/resources/docs"

